### ISSUE TITLE
[Bug] <can't install it on android>

### ISSUE THREAD

**Issue by BlackDevill11** [MerlinKodo/clash-rev#1]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash.Rev core
- [X] I am submitting an issue with the Clash.Rev core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash.Rev core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://merlinkodo.github.io/clash-rev-doc/) **and was unable to solve the issue**

### Version

clash.rev-android-arm64-go120-v1.0.0.gz, clash.rev-android-arm64-cgo-v1.0.0.gz and clash.rev-android-arm64-v1.0.0.gz

### Operating System

Android

### Architecture

arm64

### Configuration File

```YAML
.
```

### Description

Im not in expert here but i tried evey way like unzip the file and rename it with apk but still there is no way to install it on android i don't know if there are other ways or not of course if clash.rev support android if not forget what i said thank you.

**Comment by MerlinKodo** [comment]
Hi, @BlackDevill11 

Clash.Rev supports Android, but it's a CLI software, so you can't use it like a regular APK file. You should use `adb` or a terminal emulator, similar to Termux, to execute it via the command line. This can be quite challenging for average users. I recommend using a GUI program, like Clash for Android, for easier use. However, these GUI programs are currently not being maintained. I might develop one myself in the future.

The following image is a screenshot of my successful test run using adb shell on my phone.
![image](https://github.com/MerlinKodo/clash-rev/assets/150133030/7186198a-5ef9-4eb1-95aa-ec2b28b15e0c)
