### ISSUE TITLE
geox.dat可以定时自动更新吗？

### ISSUE THREAD

**Issue by sxnpu** [MerlinKodo/clash-rev#10]
### 先决条件

- [X] 我了解这里是 Clash.Rev 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/MerlinKodo/clash-rev/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](fhttps://merlinkodo.github.io/clash-rev-doc/) 

### 描述

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MerlinKodo/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MerlinKodo/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MerlinKodo/meta-rules-dat@release/country.mmdb"
这样自定义下载地址后，是否可以像rule-providers那样自动更新？Google到了类似的issue，但是meta那边是archived的状态，打不开

**Comment by MerlinKodo** [comment]
可以添加支持

**Comment by MerlinKodo** [comment]
@sxnpu  现在支持两个新的设置项`geo-auto-update`和`geo-update-interval`，启用后会定时更新geo文件，可从最新的Pre-release发布中获取二进制文件进行测试。

https://github.com/MerlinKodo/clash-rev/releases/tag/Prerelease-dev

```yaml
geo-auto-update: false # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
```
