### ISSUE TITLE
clash for windows和clash verge更换1.0.1版本不能启用[Bug] <问题标题>

### ISSUE THREAD

**Issue by oyk470p** [MerlinKodo/clash-rev#2]
### 先决条件

- [X] 我了解这里是开源版 Clash.Rev 核心仓库
- [X] 我要提交 Clash.Rev 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash.Rev 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://merlinkodo.github.io/clash-rev-doc/) 并无法自行解决问题

### 版本

1.0.1

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
无
```

### 问题描述

clash for windows和clash verge更换内核1.0.1不能启用，1.0.0正常

**Comment by ArcCal** [comment]
你怎么确认“并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题”的


再者，你怎么使用的，怎么个不能启用法（怎么报错），有没有截图，有没有日志，怎么复现



开发者不是大仙，没法根据你的一句没法启用就定位原因，也没人有这个闲心在没有任何线索的情况下进行排查

**Comment by ansemz** [comment]
我windows 10用了clash verge v1.37+clash rev v1.0.1，工作状态良好。

**Comment by MerlinKodo** [comment]
@oyk470p 感谢反馈。我的测试环境如下：

OS: windows 11
Clash for Windows版本: 0.20.39
Clash Verge版本: 1.38

经过测试，确实1.0.1版本由于修改了命令参数处理，导致与CFW无法一起工作，目前已经定位问题并进行了修复，马上会进行修复并发布1.0.2版本。Clash verge经过测试，在本机上可以正常与1.0.1一起工作，如果1.02版本仍有问题请提供更多细节。

修复后的CFW使用clash.rev内核正常工作截图如下：
![image](https://github.com/MerlinKodo/clash-rev/assets/150133030/d361ffc2-f4a5-4b53-963f-c0fd2686d833)

**Comment by oyk470p** [comment]
1.0.2for clash for windows正常使用，感谢大佬

**Comment by Joackk** [comment]
这个内核是把clash-core和clash-mete这俩融合起来了吗？有时候会遇到只支持clash内核的，或者只支持clash-mete内核的，这个是同时把上面俩都支持了吗？

**Comment by MerlinKodo** [comment]
> 这个内核是把clash-core和clash-mete这俩融合起来了吗？有时候会遇到只支持clash内核的，或者只支持clash-mete内核的，这个是同时把上面俩都支持了吗？

原Clash内核主要分三个方向，开源的clash-core, clash.meta和闭源的clash-core-premium，其中clash-core不支持tun等高级功能。
基于功能完整性考虑，本项目基于Clash.meta进行后续开发。如果有发现缺失的功能，欢迎提交issues或pr。
