### ISSUE TITLE
[Bug] <切换至clash.rev核心后cmd使用"git pull"无法拉取更新>

### ISSUE THREAD

**Issue by Amazon90** [MerlinKodo/clash-rev#8]
### 先决条件

- [X] 我了解这里是开源版 Clash.Rev 核心仓库
- [X] 我要提交 Clash.Rev 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash.Rev 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://merlinkodo.github.io/clash-rev-doc/) 并无法自行解决问题

### 版本

v1.0.2

### 适用的作业系统

Windows

### 适用的硬件架构

amd64

### 配置文件

```YAML
none
```

### 问题描述

clash for windows v0.20.39切换至clash.rev v1.0.2核心后cmd无法使用"git pull"拉取项目更新，
![20231119182802](https://github.com/MerlinKodo/clash-rev/assets/72290820/67ca2500-3bd8-4f7a-99af-74b30c3c2bfe)
![20231119182734](https://github.com/MerlinKodo/clash-rev/assets/72290820/002667bf-67a3-4e56-834e-f3214cc21f02)
![20231119182625](https://github.com/MerlinKodo/clash-rev/assets/72290820/91810b37-ce12-4d85-a09e-7b4edbd1babb)

切换回预设的clash.premium核心后问题不会发生。希望clash.rev开发者可以修复该问题。
![20231119183208](https://github.com/MerlinKodo/clash-rev/assets/72290820/aa4936f6-6737-4cbc-a89f-e1b0849e5e3c)
![20231119183226](https://github.com/MerlinKodo/clash-rev/assets/72290820/a8fcf7f0-cba0-4cd9-8b3f-920d9bd4032e)

**Comment by MerlinKodo** [comment]
尝试下使用管理员身份运行cfw，同时开启tun模式，再测试下。

更换核心后由于服务模式不兼容，所以非管理员身份下运行时下tun生效没有生效。

**Comment by Amazon90** [comment]
今天没做任何改动，又试了一下发现没问题了。
