### ISSUE TITLE
HarmonyNEXT 是否有规划

### ISSUE THREAD

**Issue by byte-creator** [MerlinKodo/clash-rev#9]
### 先决条件

- [X] 我了解这里是 Clash.Rev 官方仓库，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本
- [X] 我已经在[这里](https://github.com/MerlinKodo/clash-rev/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](fhttps://merlinkodo.github.io/clash-rev-doc/) 

### 描述

emmm，我的意思是 harmonyNEXT 有适配计划吗

**Comment by MerlinKodo** [comment]
harmony next明年一季度才开发给所有开发者，而且目前找不到太多的文档，所以暂时不考虑适配。后续会保持跟进。
